language: python
cache:
- pip
- directories:
  - node_modules
  - $HOME/.cache
os:
- linux
stages:
- phase1
- phase2
- deploy
before_install:
- nvm install $TRAVIS_NODE_VERSION
- which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --user
  tox tox-pyenv ; else python -m pip install tox tox-pyenv twine; fi
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
jobs:
  include:
  - stage: phase1
    script:
    - python setup.py sdist bdist_wheel
    - python -m tox
    env: TOXENV=lint
    python: '2.7'
    language: nodejs
    node_js:
    - '8'
  - stage: phase1
    script: python -m tox
    python: '2.7'
    env: TOXENV=docs
  - stage: phase1
    script: python -m tox
    python: '2.7'
    env: TOXENV=py27
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - requires.io update-site -t ac3bbcca32ae03237a6aae2b02eb9411045489bb -r
  - stage: phase2
    script: python -m tox
    python: '3.4'
    env: TOXENV=py34
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: phase2
    script: python -m tox
    python: '3.5'
    env: TOXENV=py35
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: phase2
    script: python -m tox
    python: '3.6'
    env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: phase2
    script: python -m pip install -q tox-travis && python -m tox
    python: '3.7'
    env: TOXENV=py37 PYTHON='3.7'
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    dist: xenial
    sudo: required
  - stage: deploy
    script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
    deploy:
    - provider: releases
      api_key:
        secure: YJGigSNYOzMJqs23gIZLFxiVYRqHdV4WsTZmRVosishD2QIaDlTwJma7k6Y5eMPVNdLpqo7Tq6bt7xkJAz/dcr3UO35T/Y0tiRFFW3sd6IOB6ELwSwPhSeHoyUMvZtKyDTl+9tOfeZusFZuCc+mBLQcG+S2NzEaeyrQ6n5hTT/8FGBP91FOq9l5q2gYbmACZ9MisDIjZkTHNYih36ComnZ9QHC91jHKcSuHmOfWWX3GneDVFtuPhF2vjaLQrz8IFtWGW5Sfe35yDYlVQRH+NFxzSJ2zDuT5j8cRgwXjGout78umtMsqAn+zv1Ws/MUNKMTEtONsACndMpGCkuB6Nifl/KcGj5kD7V4PO/gE0ecr830qAwJxSVB7xk6rl797nMxGbr4w2DWQ/iDdHDTlPAEzbLBMLrMRgPxzKPgg5CNxxjT1cHoBNcFPp6gaf017w4XOVUgp/zxXeCg7iGiNJj7z2t8/m9eYVNNlNRPcodN6BjSjPqkYxC3ZMVCI5KsRXbHmR0zOWbPdcRjrY/IgbiTqX09sHotHw5GThP6YTMbienC4h93cdx6MEfX656W6XMOxpC+MjWtYuV8QlfMEJFlstOnA86MVLcmbl+4A6FHuvlQMdDtP9KsKdKIf/4juGhNEFir32P1rUe8J1abmjwXmDkHVbli0SDqaFtB5gyCc=
      file_glob: true
      file:
      - dist/*
      - ChangeLog
      skip_cleanup: true
      true:
        tags: true
        repo: pycontribs/jira
        branch: master
env:
  global:
  - secure: pGQGM5YmHvOgaKihOyzb3k6bdqLQnZQ2OXO9QrfXlXwtop3zvZQi80Q+01l230x2psDWlwvqWTknAjAt1w463fYXPwpoSvKVCsLSSbjrf2l56nrDqnoir+n0CBy288+eIdaGEfzcxDiuULeKjlg08zrqjcjLjW0bDbBrlTXsb5U=
  - PIP_DISABLE_PIP_VERSION_CHECK=1
  - TRAVIS_NODE_VERSION="v8.11.3"
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
